### ISSUE TITLE
Please provide a license

### ISSUE THREAD

**Issue by veehaitch** [signalapp/Argon2#6]
Thanks for this project. This is very useful! 

We'd like to consider using this library for a project I'm currently working on. To that end, we first have to sort out if the licensing allows us to use it (the license of the reference implementation would work for us). Could you please add a license? Thanks!

**Comment by zanechua** [comment]
Just want to comment on this since the license still hasn't been added to the repo. I believe this repo is under the GPL 3.0 License.

They published the android equivalent to the maven repository and over there it's tagged as GPL 3.0.

https://mvnrepository.com/artifact/org.signal/argon2

**Comment by Valodim** [comment]
*Please* make this code available under Apache2/CC0, to match upstream. Libraries like this are infrastructure, I would very much appreciate if it was also available to Apache-licensed apps.

**Comment by tbrent** [comment]
@alan-signal @Imperiopolis-Signal 

Like others have said, people are eager to use better crypto in their applications and are being limited by the absence of a license. _Please_ add a license, and _please_ consider matching upstream. Doing so would help bring about a more secure world, which I expect is well in line with Signal's mission.

**Comment by Imperiopolis-Signal** [comment]
The GPLv3 license has been added.
